[build]
  functions = "functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin.html"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "14" 